# Generated by Django 2.2.2 on 2019-06-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterpiece', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpiece',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
